language: java
jdk:
  - oraclejdk8

install: true

cache:
  directories:
  - $HOME/.m2

script:
  - mvn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn package
