language: java
jdk:
- oraclejdk8
install: true
cache:
  directories:
  - "$HOME/.m2"
script:
- mvn package |  egrep -v 'Download(ing|ed)'
deploy:
  provider: releases
  api_key:
    secure: 0pqSsudLv24VWRHUYbwUaLlim4inXnRd+ZAY+/XZpz51rWvzZpV+H2oXtVYomSUhNlieleYPMx3p0/mpSwOx1xOmG1nww2nPV4IUGN6j1nzvWjHoGj92JLL06OX4EuKQ261xlzBmYaxlGVVpyzIcGxV8zVXYSdmYlwOhoGddZ7TLeXQlWppRszVdfGuWm4naObxJ+14WIjpwSB0M3692iEvXb0f1BAXdA/H21FWTQUkWTHk/v06c/W37J0UzNmYFd+v5HOBEak/tUXQ1Z5XAJ8tH1i2dAAkwjw+aa5Rqz4HTkdbrWJpfECbOdVB3zf2ifvnjC+hjFayWjjjLKnzQ+nxbvyRRxXr+IbaIifiByefZY/ZFqCdlWmlrVHijAP6DBwVAWpGWPuqbeWCTRmN9FoY/mqQGTpes3VzT5Jn+O8f24XrO+fk0pZpxfzSRFG2KxomOogllClLivivz4/vGszO+xGmk37Z1Mt5U5wl+VcE2fyF974APoQHt/NLe7KWZL0rhZCUR/hF55Xoq3gsIiBeIFiKMAxcbYR+/Hh2W7A9+7YwaIwAXT8A6dCXPr1uRfHVVYoYkTszhKnSJzeNnzinmTdFrZN2hpVV66YvSuzkAtN2qP+MqKzYZ2Ah0FdWh+qewuEvmY1VHeJoWWg+acY29rIczeAucR4UzyI0mzrI=
  file: target/tracey.hpi
  skip_cleanup: true
  on:
    tags: true
